module NaCl
  module Signatures
    module Ed25519
      SEEDBYTES      = LibSodium::CRYPTO_SIGN_ED25519_SEEDBYTES
      SIGNATUREBYTES = LibSodium::CRYPTO_SIGN_ED25519_BYTES
      VERIFYKEYBYTES = LibSodium::CRYPTO_SIGN_ED25519_PUBLICKEYBYTES
      SIGNINGKEYBYTES   = LibSodium::CRYPTO_SIGN_ED25519_SECRETKEYBYTES
    end
  end
end
